### 测试 OpenAPI 外部调用接口
POST http://localhost:8080/api/open/generate
Content-Type: application/json
X-App-Key: 7b35fff745f345a0
X-Timestamp: 1772631213974
X-Sign: 75e0d9b2110fb8ffde386166ab8d8b1f

{
  "originalUrl": "https://t.bilibili.com/?spm_id_from=333.1007.0.0"
}